### ISSUE TITLE
guru labels

### ISSUE THREAD

**Issue by spoonclaymore** [fabiogermann/guru-confluence-importer#3]
Guru has the ability for users to apply labels to articles for easy searching.
I don't see the labels in a PDF export of a collection from the Guru UI. 

Does Settings --> Content Export contain the labels? Is it possible to import the labels into Confluence?

**Comment by fabiogermann** [comment]
@spoonclaymore I haven't seen them in the exports yet. But I will doublecheck.

**Comment by fabiogermann** [comment]
@spoonclaymore a recent PR has made this possible
