### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by VAWD16** [fabiogermann/guru-confluence-importer#8]
This is the terminal output of me trying to use this tool:

```
~/Downloads > python3 guruCollectionToConfluence.py \\
  --collection-dir export-guru-IT-private/ \\
  --user user.name@email.com \\
  --api-key <API KEY<API KEY>> \\
  --space-key 'ITI' \\
  --parent 829522189 \\
  --organization orgname \\
  --date-disclaimer yes \\
  --migrate-tags yes

Traceback (most recent call last):
  File "/Users/username/Downloads/guruCollectionToConfluence.py", line 29, in <module>
    if args.migratetags is None:
       ^^^^
NameError: name 'args' is not defined
```

I'm not super familar with Python or GitHub, so any help would be appreciated.

**Comment by VAWD16** [comment]
Just an FYI. I tried this old version prior to the option for migrating tags and it worked just fine.
https://github.com/fabiogermann/guru-confluence-importer/blob/34a169e81677c695c80562bc3a18497ab7837aa4/guruCollectionToConfluence.py

**Comment by fabiogermann** [comment]
Thanks, I will have a look at this soon. Thanks for reporting it. If possible use the old version for now. I must have made a mistake during the merge of the PR.

**Comment by fabiogermann** [comment]
@VAWD16 the issue was fixed in https://github.com/fabiogermann/guru-confluence-importer/commit/5e5d8e157849020d2bbb454f518225a9e847c9db, it was a duplicate from a manual merge. Apologies for the inconvenience.
